// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/15/2026, 10:37:11 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/plugins/**/*.{js,ts,mjs}","/app/app/composables/**/*.{js,ts,mjs}","/app/app/utils/**/*.{js,ts,mjs}","/app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/app/app.config.{js,ts,mjs}"]}},
{"content":["./app/**/*.{vue,js,ts,jsx,tsx}","./app.vue"],"theme":{"extend":{"fontFamily":{"mofiwe":["Mofiwe","monospace"]},"fontSize":{"sm":["0.95rem",{"lineHeight":"1.75"}],"base":["1.125rem",{"lineHeight":"1.85"}],"lg":["1.25rem",{"lineHeight":"1.8"}],"xl":["1.5rem",{"lineHeight":"1.7"}]}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;